import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TalentCandidate, RecruiterCalculationResult, RecruiterInputs } from './recruiterTypes';
import { JobRecord, CandidateRecord, CandidateJobRecord } from './recruiterStore';
import { formatCurrency, formatPercent } from './formatters';

const BRAND_BLUE = [30, 41, 59]; // Slate 800
const ACCENT_INDIGO = [79, 70, 229]; // Indigo 600
const ACCENT_EMERALD = [16, 185, 129]; // Emerald 500

/**
 * Adds PayScope Recruit header and footer to PDF document
 */
function addPdfHeaderFooter(doc: jsPDF, title: string, pageCount: number = 1) {
  const totalPages = doc.getNumberOfPages();
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Header Bar
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(0, 0, 210, 15, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('PAYSCOPE RECRUIT', 14, 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(title, 120, 10);

    // Footer Bar
    doc.setDrawColor(226, 232, 240);
    doc.line(14, 280, 196, 280);

    doc.setTextColor(148, 163, 184); // Slate 400
    doc.setFontSize(8);
    doc.text(`Generated by PayScope Recruit · ${dateStr}`, 14, 286);
    doc.text(`Page ${i} of ${totalPages}`, 175, 286);
  }
}

/**
 * 1. Talent Search PDF Report
 */
export function generateSearchPdf(
  searchQuery: { jobTitle: string; location: string; skills: string[]; booleanString: string; xrayQuery: string },
  candidates: TalentCandidate[]
) {
  const doc = new jsPDF();

  // Title Section
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Talent Search Report', 14, 25);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Job Title: ${searchQuery.jobTitle || 'All Roles'} · Location: ${searchQuery.location || 'Any'}`, 14, 32);

  // Criteria Box
  doc.setFillColor(248, 250, 252);
  doc.rect(14, 37, 182, 30, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, 37, 182, 30, 'S');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('BOOLEAN SEARCH STRING:', 18, 44);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(searchQuery.booleanString.substring(0, 100), 18, 50);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('GOOGLE X-RAY QUERY:', 18, 57);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(searchQuery.xrayQuery.substring(0, 100), 18, 63);

  // Candidates Table
  const tableData = candidates.map((c, index) => [
    (index + 1).toString(),
    c.name,
    c.jobTitle,
    c.location,
    `${c.yearsOfExperience} yrs`,
    c.skills.slice(0, 3).join(', '),
    `${c.matchScore}%`,
  ]);

  autoTable(doc, {
    startY: 73,
    head: [['#', 'Candidate Name', 'Current Title', 'Location', 'Exp', 'Key Skills', 'Match Score']],
    body: tableData,
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 8, cellPadding: 3 },
  });

  addPdfHeaderFooter(doc, 'Talent Search Report');
  doc.save(`PayScope_Talent_Search_${searchQuery.jobTitle.replace(/\s+/g, '_')}.pdf`);
}

/**
 * 2. Job Summary & Pipeline PDF Report
 */
export function generateJobPdf(job: JobRecord, candidates: { candidate: CandidateRecord; record: CandidateJobRecord }[]) {
  const doc = new jsPDF();

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`Job Report: ${job.jobTitle}`, 14, 25);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Client: ${job.clientName} · Location: ${job.location} · Status: ${job.status}`, 14, 32);

  // Job Details Summary Box
  doc.setFillColor(248, 250, 252);
  doc.rect(14, 37, 182, 28, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, 37, 182, 28, 'S');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`Employment Type: ${job.employmentType}  |  Openings: ${job.openingsCount}  |  Exp Required: ${job.experienceRequiredYears}+ Yrs`, 18, 45);
  doc.text(`Target Pay Range: $${job.payRateRangeMin || 60} - $${job.payRateRangeMax || 80}/hr  |  Bill Rate: $${job.billRate || 90}/hr`, 18, 52);
  doc.text(`Skills Required: ${job.skillsRequired.join(', ')}`, 18, 59);

  // Candidates Pipeline Table
  const tableData = candidates.map((item, index) => [
    (index + 1).toString(),
    item.candidate.name,
    (item.candidate.headline || 'Specialist').substring(0, 30),
    `${item.candidate.yearsOfExperience || 0} yrs`,
    item.record.stage,
    item.record.l1Date ? `L1: ${item.record.l1Date}` : item.record.l2Date ? `L2: ${item.record.l2Date}` : 'N/A',
    `$${item.candidate.expectedRate || 0}/hr`,
  ]);

  autoTable(doc, {
    startY: 70,
    head: [['#', 'Candidate Name', 'Headline', 'Exp', 'Pipeline Stage', 'Interview Date', 'Pay Rate']],
    body: tableData,
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 8, cellPadding: 3 },
  });

  addPdfHeaderFooter(doc, 'Job Pipeline Report');
  doc.save(`PayScope_Job_Report_${job.jobTitle.replace(/\s+/g, '_')}.pdf`);
}

/**
 * 3. Candidate Profile PDF Report
 */
export function generateCandidatePdf(candidate: CandidateRecord, record?: CandidateJobRecord, job?: JobRecord) {
  const doc = new jsPDF();

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`Candidate Profile: ${candidate.name}`, 14, 25);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`${candidate.headline || 'Specialist'}`, 14, 32);

  // Candidate Details Card
  doc.setFillColor(248, 250, 252);
  doc.rect(14, 37, 182, 35, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, 37, 182, 35, 'S');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`Location: ${candidate.location || 'Unspecified'}  |  Exp: ${candidate.yearsOfExperience || 0} Yrs  |  Email: ${candidate.email || 'N/A'}`, 18, 45);
  doc.text(`Current Company: ${candidate.currentCompany || 'N/A'}  |  Phone: ${candidate.phone || 'N/A'}`, 18, 52);
  doc.text(`Expected Pay Rate: $${candidate.expectedRate || 0}/hr  |  Education: ${candidate.education || 'N/A'}`, 18, 59);
  doc.text(`Key Skills: ${(candidate.skills || []).join(', ')}`, 18, 66);

  let currentY = 78;

  if (record && job) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text(`Applied Position: ${job.jobTitle} (${job.clientName})`, 14, currentY);

    currentY += 6;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(`Pipeline Stage: ${record.stage}  |  Offered Rate: $${record.offeredRate || candidate.expectedRate}/hr  |  Client Bill Rate: $${record.billRate || job.billRate || 90}/hr`, 14, currentY);

    if (record.notes) {
      currentY += 6;
      doc.text(`Recruiter Notes: ${record.notes}`, 14, currentY);
    }

    currentY += 10;
    // Timeline Table
    const timelineData = record.timeline.map((t) => [t.stage, t.dateString, t.timeString || 'N/A', t.notes || 'Stage updated']);

    autoTable(doc, {
      startY: currentY,
      head: [['Pipeline Stage', 'Date Completed', 'Time', 'Notes']],
      body: timelineData,
      headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
      styles: { fontSize: 8, cellPadding: 3 },
    });
  }

  addPdfHeaderFooter(doc, 'Candidate Profile Report');
  doc.save(`PayScope_Candidate_${candidate.name.replace(/\s+/g, '_')}.pdf`);
}

/**
 * 4. Rate Calculator PDF Report
 */
export function generateRatePdf(inputs: RecruiterInputs, calc: RecruiterCalculationResult) {
  const doc = new jsPDF();

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`Rate & Margin Analysis Report`, 14, 25);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Role: ${inputs.jobTitle} · Location: ${inputs.city}, ${inputs.state}`, 14, 32);

  // Summary Metrics Grid Table
  const metricsData = [
    ['Candidate Pay Rate', `$${inputs.candidatePayRate}/hr`, 'Client Bill Rate', `$${inputs.clientBillRate}/hr`],
    ['Hourly Spread', `$${calc.spread.toFixed(2)}/hr`, 'Gross Margin %', formatPercent(calc.grossMarginPercent)],
    ['Markup %', formatPercent(calc.markupPercent), 'Margin Status', calc.marginStatus],
    ['Monthly Revenue', formatCurrency(calc.monthlyRevenue, inputs.currency), 'Monthly Gross Profit', formatCurrency(calc.monthlyGrossProfit, inputs.currency)],
    ['Annual Revenue', formatCurrency(calc.annualRevenue, inputs.currency), 'Annual Gross Profit', formatCurrency(calc.annualGrossProfit, inputs.currency)],
  ];

  autoTable(doc, {
    startY: 38,
    head: [['Metric', 'Value', 'Metric', 'Value']],
    body: metricsData,
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 4 },
  });

  // Formula Explanation Section
  let currentY = (doc as any).lastAutoTable.finalY + 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Calculation Formulas & Definitions:', 14, currentY);

  currentY += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text('• Spread = Client Bill Rate ($90/hr) - Candidate Pay Rate ($65/hr) = $25/hr', 14, currentY);
  currentY += 5;
  doc.text(`• Gross Margin = (Spread / Client Bill Rate) * 100 = ${formatPercent(calc.grossMarginPercent)} (How much remains after candidate pay)`, 14, currentY);
  currentY += 5;
  doc.text(`• Markup = (Spread / Candidate Cost) * 100 = ${formatPercent(calc.markupPercent)} (Percentage added on top of candidate pay)`, 14, currentY);

  addPdfHeaderFooter(doc, 'Rate & Margin Report');
  doc.save(`PayScope_Rate_Report_${inputs.jobTitle.replace(/\s+/g, '_')}.pdf`);
}

/**
 * 5. Full PayScope Interactive Financial Snapshot PDF Report (Excel-Style Statement & Visual Expense Bars)
 */
export function generateFinancialSnapshotPdf(snapshot: any) {
  const doc = new jsPDF();
  const { inputs, tax, economic } = snapshot;

  const currency = inputs.currency || 'USD';
  const hoursPerWeek = inputs.workHoursPerWeek || 40;
  const weeksPerYear = inputs.weeksPerYear || 52;
  const totalHours = hoursPerWeek * weeksPerYear;

  // Header Green Bar
  doc.setFillColor(31, 143, 104); // PayScope Green #1F8F68
  doc.rect(0, 0, 210, 16, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('PAYSCOPE FINANCIAL SNAPSHOT REPORT', 14, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`${new Date().toLocaleDateString()}`, 165, 11);

  // Profile Summary Box
  doc.setFillColor(243, 251, 247);
  doc.rect(14, 22, 182, 28, 'F');
  doc.setDrawColor(191, 229, 211);
  doc.rect(14, 22, 182, 28, 'S');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(18, 55, 42);
  doc.text(`Location: ${economic.cityLabel || inputs.city || 'Austin'}, ${inputs.state}, ${inputs.country}`, 18, 30);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Employment Type: ${inputs.employmentType}  |  Hours Worked: ${totalHours} hrs/yr (${hoursPerWeek} hrs/wk)`, 18, 37);
  doc.text(`Filing Status: ${inputs.filingStatus}  |  Dependents: ${inputs.dependents}`, 18, 43);

  // Excel-Sheet Style Table (Financial Income Statement)
  const excelTableRows = [
    ['Gross Revenue / Annual Income', formatCurrency(tax.annualGross, currency), formatCurrency(tax.monthlyGross, currency), '100.0%'],
    ['Federal Income Tax', `-${formatCurrency(tax.federalTax, currency)}`, `-${formatCurrency(tax.federalTax / 12, currency)}`, `${formatPercent(tax.federalTaxPercentage)}`],
    [`State/Provincial Tax (${inputs.state})`, `-${formatCurrency(tax.stateTax, currency)}`, `-${formatCurrency(tax.stateTax / 12, currency)}`, `${formatPercent(tax.stateTaxPercentage)}`],
    ['Social Security / Pension / CPP', `-${formatCurrency(tax.socialSecurityTax, currency)}`, `-${formatCurrency(tax.socialSecurityTax / 12, currency)}`, `${formatPercent(tax.socialSecurityTaxPercentage)}`],
    ['Medicare / EI Insurance', `-${formatCurrency(tax.medicareTax, currency)}`, `-${formatCurrency(tax.medicareTax / 12, currency)}`, `${formatPercent(tax.medicareTaxPercentage)}`],
  ];

  if (tax.businessExpenses > 0) {
    excelTableRows.push(['Business Expense Write-offs', `-${formatCurrency(tax.businessExpenses, currency)}`, `-${formatCurrency(tax.businessExpenses / 12, currency)}`, `${formatPercent((tax.businessExpenses / tax.annualGross) * 100)}`]);
  }

  // Summary Row: Net Take Home Pay
  excelTableRows.push(['NET TAKE-HOME PAY (AFTER TAX)', formatCurrency(tax.takeHomePayAnnual, currency), formatCurrency(tax.takeHomePayMonthly, currency), `${formatPercent(tax.takeHomePercentage)}`]);

  // Expenses Row: Estimated Monthly Cost of Living
  const colMonthly = economic.colTotalMonthly || 2400;
  const fuelMonthly = inputs.country === 'CA' ? 144 : 85.6;
  const totalMonthlyExpenses = colMonthly + fuelMonthly;
  const annualExpenses = totalMonthlyExpenses * 12;
  const disposableMonthly = Math.max(0, tax.takeHomePayMonthly - totalMonthlyExpenses);
  const disposableAnnual = disposableMonthly * 12;

  excelTableRows.push(['Estimated Living & Housing Expenses', `-${formatCurrency(annualExpenses, currency)}`, `-${formatCurrency(totalMonthlyExpenses, currency)}`, `${formatPercent((annualExpenses / tax.annualGross) * 100)}`]);
  excelTableRows.push(['NET DISPOSABLE SAVINGS', formatCurrency(disposableAnnual, currency), formatCurrency(disposableMonthly, currency), `${formatPercent((disposableAnnual / tax.annualGross) * 100)}`]);

  autoTable(doc, {
    startY: 55,
    head: [['Financial Statement Item', 'Annual Amount', 'Monthly Amount', '% of Gross']],
    body: excelTableRows,
    headStyles: { fillColor: [31, 143, 104], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [243, 251, 247] },
    styles: { fontSize: 8.5, cellPadding: 3.5, font: 'helvetica' },
    didParseCell: function(data) {
      if (data.row.index === excelTableRows.length - 3 || data.row.index === excelTableRows.length - 1) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [234, 247, 241];
        data.cell.styles.textColor = [18, 55, 42];
      }
    }
  });

  let currentY = (doc as any).lastAutoTable.finalY + 12;

  // Expense Visual Breakdown Bars Section
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(18, 55, 42);
  doc.text('Expense & Income Allocation Breakdown Bars', 14, currentY);

  currentY += 8;

  const barCategories = [
    { label: 'Net Take-Home Pay', pct: Math.min(100, Math.max(0, tax.takeHomePercentage)), color: [31, 143, 104] },
    { label: 'Taxes & Deductions', pct: Math.min(100, Math.max(0, tax.effectiveTaxRate)), color: [239, 68, 68] },
    { label: 'Living & Housing Expenses', pct: Math.min(100, Math.max(0, (annualExpenses / tax.annualGross) * 100)), color: [245, 158, 11] },
    { label: 'Remaining Savings Margin', pct: Math.min(100, Math.max(0, (disposableAnnual / tax.annualGross) * 100)), color: [59, 130, 246] },
  ];

  barCategories.forEach((cat) => {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(`${cat.label}: ${cat.pct.toFixed(1)}%`, 14, currentY);

    // Draw background gray bar
    doc.setFillColor(226, 232, 240);
    doc.rect(80, currentY - 3.5, 100, 4, 'F');

    // Draw active colored bar
    doc.setFillColor(cat.color[0], cat.color[1], cat.color[2]);
    doc.rect(80, currentY - 3.5, Math.max(2, (cat.pct / 100) * 100), 4, 'F');

    currentY += 8;
  });

  // Footer Notice
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by PayScope Statutory Financial Engine · Official 2026 Tax Rules · Page 1 of 1`, 14, 285);

  doc.save(`PayScope_Financial_Snapshot_${(inputs.city || 'Result').replace(/\s+/g, '_')}.pdf`);
}

